#Este es el perfil de dev, puedo crear diferentes perfiles configurando el nombre del archivo, ejemplo application-nombre
#Creamos todo lo que sea especifico para este perfil
server.port=8090

#Spring Data JPA (Conmfiguracion de la base de datos para dev)
spring.datasource.url=jdbc:postgresql://localhost:5432/platzi_camilo_db
spring.datasource.username=camilo
spring.datasource.password=camilo

# Esta parte hace que si no está creada la tabla se cree automaticamente y no de error, pero si ya está creada no la borra ni nada, solo la actualiza
spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.sql.init.mode=always

#langchain4j
langchain4j.open-ai.chat-model.api-key=demo
#Activamos los logs para que se vean cuando se ejecute la app
langchain4j.open-ai.chat-model.log-requests=true
langchain4j.open-ai.chat-model.log-responses=true
logging.level.dev.langchain4j=DEBUG
logging.level.dev.ai4j.openai4j=DEBUG

