#Este es el perfil de prod, puedo crear diferentes perfiles configurando el nombre del archivo, ejemplo application-nombre
#Creamos todo lo que sea especifico para este perfil
server.port=8080

#langchain4j
langchain4j.open-ai.chat-model.api-key=demo


