# En este archivo va todo lo que sea general

#Aca decimos el perfil en el cual se va a ejecutar
spring.profiles.active=dev

spring.application.name=platzi-camilo
server.servlet.context-path=/platzi-play/api

#langchain4j
langchain4j.open-ai.chat-model.model-name=gpt-4o-mini

#Spring Data JPA  (Base de datos)
spring.datasource.driver-class-name=org.postgresql.Driver

